language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
branches:
  only:
  - master
script:
- ./deploy.sh
cache:
  directories:
  - node_modules
env:
  global:
    secure: Tr1vTRtwP0ldMTqa8hiYFYoQhvr4EZSvKBEUHgq9M4WZ71jzR4hY2lVv+UCDy+Ju34vvhDXHcSZcS5/NygjOq0yTHa1VHTRL3oo1V5OPlzWb8Efh96avzIAtpEovAzjemWge6Q9t7odMIvSGXS5UtmALv5ChVVvG2fDRPWuKv7k=