language: node_js
node_js:
- '5'
script:
- npm run test
- grunt eslint
before_script:
  - npm install grunt-cli -g
sudo: false
branches:
  only:
  - master
after_success:
- npm run deploy
cache:
  directories:
  - node_modules
env:
  global:
  - secure: e19W21p8kMLplqVSaTYkRfJ4M4+zF2mU0g+/MuCn4+R7NlYV4VVAUDAzMTX2pipdfezO1hEbX44T2GWY2XyeZ3qf37YAqA9qZsegS4lt4fgPO8ltEUSx2JDgAG8zIPMZy+gEl0mrY/xg/nlb+U1OtwdDWF0ljIjVzaTe2AuTduc=
notifications:
  hipchat:
    rooms:
      secure: TenksGLcXSWdGbscxTtD1lPRSvt/xskjOn2LSkWImzR5+Wo0v9Xorj79xE/f7ifJ2LKCQwMEQlkT5OVZ5kte7tjrNPiC00PB6Fsdniu+BdTn8k3s6TBD+iZrakMtLJ7+7i67fKul+y4NJDgz4454TiFhL4EmUhgNF+JCsO1UVDE=
    template:
      - '%{repository_slug}#%{build_number} (%{author}): %{commit_message} (<a href="%{compare_url}">%{commit}</a>)'
    format: html