language: node_js
node_js:
- '0.12'
before_script:
- npm install -g grunt-cli
script:
- npm run test
- grunt jshint
sudo: false
branches:
  only:
  - master
after_success:
- npm run deploy
cache:
  directories:
  - node_modules
env:
  global:
  - secure: moZ+HIGrWb3Qi6OGD7J/uPsZdaTL7qwjDUkOy7mULbxCqY1Wf1ICWp+wf/mPmy5lmAeJOv3WYBUYebwB7Ypxr/4eAH/hwBfke0Wge/T0TWRiQEKx/xiMCDAKA8ErbqtgQ6i7hxiSXsE0O/Ax1KTa2JU/3sASzkPEDgDAr3zwc4Q=
notifications:
  hipchat:
    rooms:
      secure: TenksGLcXSWdGbscxTtD1lPRSvt/xskjOn2LSkWImzR5+Wo0v9Xorj79xE/f7ifJ2LKCQwMEQlkT5OVZ5kte7tjrNPiC00PB6Fsdniu+BdTn8k3s6TBD+iZrakMtLJ7+7i67fKul+y4NJDgz4454TiFhL4EmUhgNF+JCsO1UVDE=
    template:
      - '%{repository_slug}#%{build_number} (%{author}): %{commit_message} (<a href="%{compare_url}">%{commit}</a>)'
    format: html